name: El blog <i>del Partido Digital</i>
description: Transparencia y m치s participaci칩n. Una entrada a la vez.
meta_description: "El blog del Partido Digital. Transparencia y m치s participaci칩n."
title: El blog del Partido Digital

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.partidodigital.org.uy'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

url: 'http://blog.partidodigital.org.uy'
